-- Script para criar a tabela Veiculo no banco SQLite
CREATE TABLE IF NOT EXISTS Veiculo (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Chassi TEXT,
    Placa TEXT NOT NULL,
    UsaGasolina BOOLEAN NOT NULL DEFAULT 0,
    UsaEtanol BOOLEAN NOT NULL DEFAULT 0,
    UsaGNV BOOLEAN NOT NULL DEFAULT 0,
    UsaRecargaEletrica BOOLEAN NOT NULL DEFAULT 0,
    UsaDiesel BOOLEAN NOT NULL DEFAULT 0,
    UsaHidrogenio BOOLEAN NOT NULL DEFAULT 0,
    Marca TEXT NOT NULL,
    Modelo TEXT NOT NULL,
    AnoFabricacao INTEGER NOT NULL,
    AnoModelo INTEGER NOT NULL,
    Cor TEXT,
    Motor TEXT,
    Cilindrada TEXT,
    Potencia TEXT,
    Importado BOOLEAN NOT NULL DEFAULT 0,
    UfOrigemId INTEGER NOT NULL,
    UfAtualId INTEGER NOT NULL,
    MunicipioOrigem TEXT NOT NULL,
    MunicipioAtual TEXT NOT NULL,
    Segmento TEXT,
    EspecieVeiculo TEXT,
    Passageiros INTEGER NOT NULL DEFAULT 0,
    Observacoes TEXT,
    Personalizacao TEXT,
    FOREIGN KEY (UfOrigemId) REFERENCES UF(Id),
    FOREIGN KEY (UfAtualId) REFERENCES UF(Id)
);
